// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/getting/common/page.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASCE        SortDirection = 1
	SortDirection_SORT_DIRECTION_DESC        SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASCE",
		2: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASCE":        1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_getting_common_page_proto_enumTypes[0].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_proto_getting_common_page_proto_enumTypes[0]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_getting_common_page_proto_rawDescGZIP(), []int{0}
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBys       []*SortBy              `protobuf:"bytes,3,rep,name=sort_bys,json=sortBys,proto3" json:"sort_bys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_getting_common_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_common_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_getting_common_page_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetSortBys() []*SortBy {
	if x != nil {
		return x.SortBys
	}
	return nil
}

type SortBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction     SortDirection          `protobuf:"varint,2,opt,name=direction,proto3,enum=getting.common.SortDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortBy) Reset() {
	*x = SortBy{}
	mi := &file_proto_getting_common_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortBy) ProtoMessage() {}

func (x *SortBy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_common_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortBy.ProtoReflect.Descriptor instead.
func (*SortBy) Descriptor() ([]byte, []int) {
	return file_proto_getting_common_page_proto_rawDescGZIP(), []int{1}
}

func (x *SortBy) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortBy) GetDirection() SortDirection {
	if x != nil {
		return x.Direction
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

var File_proto_getting_common_page_proto protoreflect.FileDescriptor

const file_proto_getting_common_page_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/getting/common/page.proto\x12\x0egetting.common\"p\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x121\n" +
	"\bsort_bys\x18\x03 \x03(\v2\x16.getting.common.SortByR\asortBys\"[\n" +
	"\x06SortBy\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12;\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1d.getting.common.SortDirectionR\tdirection*a\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SORT_DIRECTION_ASCE\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x02B\xb3\x01\n" +
	"\x12com.getting.commonB\tPageProtoP\x01Z9github.com/tsingson/grpc-rust-buf/go/proto/getting/common\xa2\x02\x03GCX\xaa\x02\x0eGetting.Common\xca\x02\x0eGetting\\Common\xe2\x02\x1aGetting\\Common\\GPBMetadata\xea\x02\x0fGetting::Commonb\x06proto3"

var (
	file_proto_getting_common_page_proto_rawDescOnce sync.Once
	file_proto_getting_common_page_proto_rawDescData []byte
)

func file_proto_getting_common_page_proto_rawDescGZIP() []byte {
	file_proto_getting_common_page_proto_rawDescOnce.Do(func() {
		file_proto_getting_common_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_getting_common_page_proto_rawDesc), len(file_proto_getting_common_page_proto_rawDesc)))
	})
	return file_proto_getting_common_page_proto_rawDescData
}

var file_proto_getting_common_page_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_getting_common_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_getting_common_page_proto_goTypes = []any{
	(SortDirection)(0), // 0: getting.common.SortDirection
	(*Pagination)(nil), // 1: getting.common.Pagination
	(*SortBy)(nil),     // 2: getting.common.SortBy
}
var file_proto_getting_common_page_proto_depIdxs = []int32{
	2, // 0: getting.common.Pagination.sort_bys:type_name -> getting.common.SortBy
	0, // 1: getting.common.SortBy.direction:type_name -> getting.common.SortDirection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_getting_common_page_proto_init() }
func file_proto_getting_common_page_proto_init() {
	if File_proto_getting_common_page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_getting_common_page_proto_rawDesc), len(file_proto_getting_common_page_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_getting_common_page_proto_goTypes,
		DependencyIndexes: file_proto_getting_common_page_proto_depIdxs,
		EnumInfos:         file_proto_getting_common_page_proto_enumTypes,
		MessageInfos:      file_proto_getting_common_page_proto_msgTypes,
	}.Build()
	File_proto_getting_common_page_proto = out.File
	file_proto_getting_common_page_proto_goTypes = nil
	file_proto_getting_common_page_proto_depIdxs = nil
}
