// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.ts"
// @generated from file proto/getting/v1/auth.proto (package getting.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/getting/v1/auth.proto.
 */
export const file_proto_getting_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("Chtwcm90by9nZXR0aW5nL3YxL2F1dGgucHJvdG8SCmdldHRpbmcudjEiMAoNU2lnbmluUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSJRCg5TaWduaW5SZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSKQoKdG9rZW5fdHlwZRgCIAEoDjIVLmdldHRpbmcudjEuVG9rZW5UeXBlIjAKDVNpZ251cFJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiQAoOU2lnbnVwUmVzcG9uc2USDAoEY29kZRgBIAEoBRIUCgdtZXNzYWdlGAIgASgJSACIAQFCCgoIX21lc3NhZ2UqPgoJVG9rZW5UeXBlEhoKFlRPS0VOX1RZUEVfVU5TUEVDSUZJRUQQABIVChFUT0tFTl9UWVBFX0JFQVJFUhABMowBCgRBdXRoEkEKBlNpZ25pbhIZLmdldHRpbmcudjEuU2lnbmluUmVxdWVzdBoaLmdldHRpbmcudjEuU2lnbmluUmVzcG9uc2UiABJBCgZTaWdudXASGS5nZXR0aW5nLnYxLlNpZ251cFJlcXVlc3QaGi5nZXR0aW5nLnYxLlNpZ251cFJlc3BvbnNlIgBCpQEKDmNvbS5nZXR0aW5nLnYxQglBdXRoUHJvdG9QAVo/Z2l0aHViLmNvbS90c2luZ3Nvbi9ncnBjLXJ1c3QtYnVmL2dvL3Byb3RvL2dldHRpbmcvdjE7Z2V0dGluZ3YxogIDR1hYqgIKR2V0dGluZy5WMcoCCkdldHRpbmdcVjHiAhZHZXR0aW5nXFYxXEdQQk1ldGFkYXRh6gILR2V0dGluZzo6VjFiBnByb3RvMw");

/**
 * @generated from message getting.v1.SigninRequest
 */
export type SigninRequest = Message<"getting.v1.SigninRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message getting.v1.SigninRequest.
 * Use `create(SigninRequestSchema)` to create a new message.
 */
export const SigninRequestSchema: GenMessage<SigninRequest> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_auth, 0);

/**
 * @generated from message getting.v1.SigninResponse
 */
export type SigninResponse = Message<"getting.v1.SigninResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: getting.v1.TokenType token_type = 2;
   */
  tokenType: TokenType;
};

/**
 * Describes the message getting.v1.SigninResponse.
 * Use `create(SigninResponseSchema)` to create a new message.
 */
export const SigninResponseSchema: GenMessage<SigninResponse> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_auth, 1);

/**
 * @generated from message getting.v1.SignupRequest
 */
export type SignupRequest = Message<"getting.v1.SignupRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message getting.v1.SignupRequest.
 * Use `create(SignupRequestSchema)` to create a new message.
 */
export const SignupRequestSchema: GenMessage<SignupRequest> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_auth, 2);

/**
 * @generated from message getting.v1.SignupResponse
 */
export type SignupResponse = Message<"getting.v1.SignupResponse"> & {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: optional string message = 2;
   */
  message?: string;
};

/**
 * Describes the message getting.v1.SignupResponse.
 * Use `create(SignupResponseSchema)` to create a new message.
 */
export const SignupResponseSchema: GenMessage<SignupResponse> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_auth, 3);

/**
 * @generated from enum getting.v1.TokenType
 */
export enum TokenType {
  /**
   * @generated from enum value: TOKEN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TOKEN_TYPE_BEARER = 1;
   */
  BEARER = 1,
}

/**
 * Describes the enum getting.v1.TokenType.
 */
export const TokenTypeSchema: GenEnum<TokenType> = /*@__PURE__*/
  enumDesc(file_proto_getting_v1_auth, 0);

/**
 * @generated from service getting.v1.Auth
 */
export const Auth: GenService<{
  /**
   * @generated from rpc getting.v1.Auth.Signin
   */
  signin: {
    methodKind: "unary";
    input: typeof SigninRequestSchema;
    output: typeof SigninResponseSchema;
  },
  /**
   * @generated from rpc getting.v1.Auth.Signup
   */
  signup: {
    methodKind: "unary";
    input: typeof SignupRequestSchema;
    output: typeof SignupResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_getting_v1_auth, 0);

