// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.ts"
// @generated from file proto/getting/v1/user.proto (package getting.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "../basic_pb.ts";
import { file_proto_getting_basic } from "../basic_pb.ts";
import type { Pagination } from "../common/page_pb.ts";
import { file_proto_getting_common_page } from "../common/page_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/getting/v1/user.proto.
 */
export const file_proto_getting_v1_user: GenFile = /*@__PURE__*/
  fileDesc("Chtwcm90by9nZXR0aW5nL3YxL3VzZXIucHJvdG8SCmdldHRpbmcudjEiXwoHVXNlckR0bxIKCgJpZBgBIAEoAxINCgVlbWFpbBgCIAEoCRIRCgRuYW1lGAMgASgJSACIAQESDgoGc3RhdHVzGAQgASgFEg0KBWN0aW1lGAUgASgDQgcKBV9uYW1lIhwKDkdldFVzZXJSZXF1ZXN0EgoKAmlkGAEgASgDIn0KD1BhZ2VVc2VyUmVxdWVzdBIuCgpwYWdpbmF0aW9uGAEgASgLMhouZ2V0dGluZy5jb21tb24uUGFnaW5hdGlvbhIRCgRuYW1lGAIgASgJSACIAQESEwoGc3RhdHVzGAMgASgFSAGIAQFCBwoFX25hbWVCCQoHX3N0YXR1cyJbChFVcGRhdGVVc2VyUmVxdWVzdBIKCgJpZBgBIAEoAxIRCgRuYW1lGAIgASgJSACIAQESEwoGc3RhdHVzGAMgASgFSAGIAQFCBwoFX25hbWVCCQoHX3N0YXR1cyJPChFTdHJlYW1MaXN0UmVxdWVzdBIRCgRuYW1lGAIgASgJSACIAQESEwoGc3RhdHVzGAMgASgFSAGIAQFCBwoFX25hbWVCCQoHX3N0YXR1czLBAQoEVXNlchI4CgNHZXQSGi5nZXR0aW5nLnYxLkdldFVzZXJSZXF1ZXN0GhMuZ2V0dGluZy52MS5Vc2VyRHRvIgASOQoGVXBkYXRlEh0uZ2V0dGluZy52MS5VcGRhdGVVc2VyUmVxdWVzdBoOLmdldHRpbmcuRW1wdHkiABJECgpTdHJlYW1MaXN0Eh0uZ2V0dGluZy52MS5TdHJlYW1MaXN0UmVxdWVzdBoTLmdldHRpbmcudjEuVXNlckR0byIAMAFCpQEKDmNvbS5nZXR0aW5nLnYxQglVc2VyUHJvdG9QAVo/Z2l0aHViLmNvbS90c2luZ3Nvbi9ncnBjLXJ1c3QtYnVmL2dvL3Byb3RvL2dldHRpbmcvdjE7Z2V0dGluZ3YxogIDR1hYqgIKR2V0dGluZy5WMcoCCkdldHRpbmdcVjHiAhZHZXR0aW5nXFYxXEdQQk1ldGFkYXRh6gILR2V0dGluZzo6VjFiBnByb3RvMw", [file_proto_getting_basic, file_proto_getting_common_page]);

/**
 * @generated from message getting.v1.UserDto
 */
export type UserDto = Message<"getting.v1.UserDto"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: optional string name = 3;
   */
  name?: string;

  /**
   * @generated from field: int32 status = 4;
   */
  status: number;

  /**
   * epoch time in milliseconds
   *
   * @generated from field: int64 ctime = 5;
   */
  ctime: bigint;
};

/**
 * Describes the message getting.v1.UserDto.
 * Use `create(UserDtoSchema)` to create a new message.
 */
export const UserDtoSchema: GenMessage<UserDto> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_user, 0);

/**
 * @generated from message getting.v1.GetUserRequest
 */
export type GetUserRequest = Message<"getting.v1.GetUserRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message getting.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_user, 1);

/**
 * @generated from message getting.v1.PageUserRequest
 */
export type PageUserRequest = Message<"getting.v1.PageUserRequest"> & {
  /**
   * @generated from field: getting.common.Pagination pagination = 1;
   */
  pagination?: Pagination;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional int32 status = 3;
   */
  status?: number;
};

/**
 * Describes the message getting.v1.PageUserRequest.
 * Use `create(PageUserRequestSchema)` to create a new message.
 */
export const PageUserRequestSchema: GenMessage<PageUserRequest> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_user, 2);

/**
 * @generated from message getting.v1.UpdateUserRequest
 */
export type UpdateUserRequest = Message<"getting.v1.UpdateUserRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional int32 status = 3;
   */
  status?: number;
};

/**
 * Describes the message getting.v1.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema: GenMessage<UpdateUserRequest> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_user, 3);

/**
 * @generated from message getting.v1.StreamListRequest
 */
export type StreamListRequest = Message<"getting.v1.StreamListRequest"> & {
  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional int32 status = 3;
   */
  status?: number;
};

/**
 * Describes the message getting.v1.StreamListRequest.
 * Use `create(StreamListRequestSchema)` to create a new message.
 */
export const StreamListRequestSchema: GenMessage<StreamListRequest> = /*@__PURE__*/
  messageDesc(file_proto_getting_v1_user, 4);

/**
 * @generated from service getting.v1.User
 */
export const User: GenService<{
  /**
   * @generated from rpc getting.v1.User.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof UserDtoSchema;
  },
  /**
   * @generated from rpc getting.v1.User.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc getting.v1.User.StreamList
   */
  streamList: {
    methodKind: "server_streaming";
    input: typeof StreamListRequestSchema;
    output: typeof UserDtoSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_getting_v1_user, 0);

