// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.ts"
// @generated from file proto/getting/basic.proto (package getting, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/getting/basic.proto.
 */
export const file_proto_getting_basic: GenFile = /*@__PURE__*/
  fileDesc("Chlwcm90by9nZXR0aW5nL2Jhc2ljLnByb3RvEgdnZXR0aW5nIgcKBUVtcHR5QokBCgtjb20uZ2V0dGluZ0IKQmFzaWNQcm90b1ABWjJnaXRodWIuY29tL3RzaW5nc29uL2dycGMtcnVzdC1idWYvZ28vcHJvdG8vZ2V0dGluZ6ICA0dYWKoCB0dldHRpbmfKAgdHZXR0aW5n4gITR2V0dGluZ1xHUEJNZXRhZGF0YeoCB0dldHRpbmdiBnByb3RvMw");

/**
 * @generated from message getting.Empty
 */
export type Empty = Message<"getting.Empty"> & {
};

/**
 * Describes the message getting.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_proto_getting_basic, 0);

