// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/getting/v1/auth.proto

package gettingv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/tsingson/grpc-rust-buf/go/proto/getting/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthName is the fully-qualified name of the Auth service.
	AuthName = "getting.v1.Auth"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthSigninProcedure is the fully-qualified name of the Auth's Signin RPC.
	AuthSigninProcedure = "/getting.v1.Auth/Signin"
	// AuthSignupProcedure is the fully-qualified name of the Auth's Signup RPC.
	AuthSignupProcedure = "/getting.v1.Auth/Signup"
)

// AuthClient is a client for the getting.v1.Auth service.
type AuthClient interface {
	Signin(context.Context, *connect.Request[v1.SigninRequest]) (*connect.Response[v1.SigninResponse], error)
	Signup(context.Context, *connect.Request[v1.SignupRequest]) (*connect.Response[v1.SignupResponse], error)
}

// NewAuthClient constructs a client for the getting.v1.Auth service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authMethods := v1.File_proto_getting_v1_auth_proto.Services().ByName("Auth").Methods()
	return &authClient{
		signin: connect.NewClient[v1.SigninRequest, v1.SigninResponse](
			httpClient,
			baseURL+AuthSigninProcedure,
			connect.WithSchema(authMethods.ByName("Signin")),
			connect.WithClientOptions(opts...),
		),
		signup: connect.NewClient[v1.SignupRequest, v1.SignupResponse](
			httpClient,
			baseURL+AuthSignupProcedure,
			connect.WithSchema(authMethods.ByName("Signup")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authClient implements AuthClient.
type authClient struct {
	signin *connect.Client[v1.SigninRequest, v1.SigninResponse]
	signup *connect.Client[v1.SignupRequest, v1.SignupResponse]
}

// Signin calls getting.v1.Auth.Signin.
func (c *authClient) Signin(ctx context.Context, req *connect.Request[v1.SigninRequest]) (*connect.Response[v1.SigninResponse], error) {
	return c.signin.CallUnary(ctx, req)
}

// Signup calls getting.v1.Auth.Signup.
func (c *authClient) Signup(ctx context.Context, req *connect.Request[v1.SignupRequest]) (*connect.Response[v1.SignupResponse], error) {
	return c.signup.CallUnary(ctx, req)
}

// AuthHandler is an implementation of the getting.v1.Auth service.
type AuthHandler interface {
	Signin(context.Context, *connect.Request[v1.SigninRequest]) (*connect.Response[v1.SigninResponse], error)
	Signup(context.Context, *connect.Request[v1.SignupRequest]) (*connect.Response[v1.SignupResponse], error)
}

// NewAuthHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthHandler(svc AuthHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authMethods := v1.File_proto_getting_v1_auth_proto.Services().ByName("Auth").Methods()
	authSigninHandler := connect.NewUnaryHandler(
		AuthSigninProcedure,
		svc.Signin,
		connect.WithSchema(authMethods.ByName("Signin")),
		connect.WithHandlerOptions(opts...),
	)
	authSignupHandler := connect.NewUnaryHandler(
		AuthSignupProcedure,
		svc.Signup,
		connect.WithSchema(authMethods.ByName("Signup")),
		connect.WithHandlerOptions(opts...),
	)
	return "/getting.v1.Auth/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthSigninProcedure:
			authSigninHandler.ServeHTTP(w, r)
		case AuthSignupProcedure:
			authSignupHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthHandler struct{}

func (UnimplementedAuthHandler) Signin(context.Context, *connect.Request[v1.SigninRequest]) (*connect.Response[v1.SigninResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("getting.v1.Auth.Signin is not implemented"))
}

func (UnimplementedAuthHandler) Signup(context.Context, *connect.Request[v1.SignupRequest]) (*connect.Response[v1.SignupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("getting.v1.Auth.Signup is not implemented"))
}
