// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/getting/v1/auth.proto

package gettingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenType int32

const (
	TokenType_TOKEN_TYPE_UNSPECIFIED TokenType = 0
	TokenType_TOKEN_TYPE_BEARER      TokenType = 1
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "TOKEN_TYPE_UNSPECIFIED",
		1: "TOKEN_TYPE_BEARER",
	}
	TokenType_value = map[string]int32{
		"TOKEN_TYPE_UNSPECIFIED": 0,
		"TOKEN_TYPE_BEARER":      1,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_getting_v1_auth_proto_enumTypes[0].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_proto_getting_v1_auth_proto_enumTypes[0]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_proto_getting_v1_auth_proto_rawDescGZIP(), []int{0}
}

type SigninRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigninRequest) Reset() {
	*x = SigninRequest{}
	mi := &file_proto_getting_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigninRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninRequest) ProtoMessage() {}

func (x *SigninRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninRequest.ProtoReflect.Descriptor instead.
func (*SigninRequest) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SigninRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SigninRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SigninResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     TokenType              `protobuf:"varint,2,opt,name=token_type,json=tokenType,proto3,enum=proto.getting.v1.TokenType" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigninResponse) Reset() {
	*x = SigninResponse{}
	mi := &file_proto_getting_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigninResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninResponse) ProtoMessage() {}

func (x *SigninResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninResponse.ProtoReflect.Descriptor instead.
func (*SigninResponse) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SigninResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SigninResponse) GetTokenType() TokenType {
	if x != nil {
		return x.TokenType
	}
	return TokenType_TOKEN_TYPE_UNSPECIFIED
}

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_proto_getting_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_proto_getting_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SignupResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SignupResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_proto_getting_v1_auth_proto protoreflect.FileDescriptor

const file_proto_getting_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/getting/v1/auth.proto\x12\x10proto.getting.v1\"A\n" +
	"\rSigninRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"o\n" +
	"\x0eSigninResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12:\n" +
	"\n" +
	"token_type\x18\x02 \x01(\x0e2\x1b.proto.getting.v1.TokenTypeR\ttokenType\"A\n" +
	"\rSignupRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"O\n" +
	"\x0eSignupResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message*>\n" +
	"\tTokenType\x12\x1a\n" +
	"\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TOKEN_TYPE_BEARER\x10\x012\xa4\x01\n" +
	"\x04Auth\x12M\n" +
	"\x06Signin\x12\x1f.proto.getting.v1.SigninRequest\x1a .proto.getting.v1.SigninResponse\"\x00\x12M\n" +
	"\x06Signup\x12\x1f.proto.getting.v1.SignupRequest\x1a .proto.getting.v1.SignupResponse\"\x00B\xc4\x01\n" +
	"\x14com.proto.getting.v1B\tAuthProtoP\x01Z?github.com/tsingson/grpc-rust-buf/go/proto/getting/v1;gettingv1\xa2\x02\x03PGX\xaa\x02\x10Proto.Getting.V1\xca\x02\x10Proto\\Getting\\V1\xe2\x02\x1cProto\\Getting\\V1\\GPBMetadata\xea\x02\x12Proto::Getting::V1b\x06proto3"

var (
	file_proto_getting_v1_auth_proto_rawDescOnce sync.Once
	file_proto_getting_v1_auth_proto_rawDescData []byte
)

func file_proto_getting_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_getting_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_getting_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_getting_v1_auth_proto_rawDesc), len(file_proto_getting_v1_auth_proto_rawDesc)))
	})
	return file_proto_getting_v1_auth_proto_rawDescData
}

var file_proto_getting_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_getting_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_getting_v1_auth_proto_goTypes = []any{
	(TokenType)(0),         // 0: proto.getting.v1.TokenType
	(*SigninRequest)(nil),  // 1: proto.getting.v1.SigninRequest
	(*SigninResponse)(nil), // 2: proto.getting.v1.SigninResponse
	(*SignupRequest)(nil),  // 3: proto.getting.v1.SignupRequest
	(*SignupResponse)(nil), // 4: proto.getting.v1.SignupResponse
}
var file_proto_getting_v1_auth_proto_depIdxs = []int32{
	0, // 0: proto.getting.v1.SigninResponse.token_type:type_name -> proto.getting.v1.TokenType
	1, // 1: proto.getting.v1.Auth.Signin:input_type -> proto.getting.v1.SigninRequest
	3, // 2: proto.getting.v1.Auth.Signup:input_type -> proto.getting.v1.SignupRequest
	2, // 3: proto.getting.v1.Auth.Signin:output_type -> proto.getting.v1.SigninResponse
	4, // 4: proto.getting.v1.Auth.Signup:output_type -> proto.getting.v1.SignupResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_getting_v1_auth_proto_init() }
func file_proto_getting_v1_auth_proto_init() {
	if File_proto_getting_v1_auth_proto != nil {
		return
	}
	file_proto_getting_v1_auth_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_getting_v1_auth_proto_rawDesc), len(file_proto_getting_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_getting_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_getting_v1_auth_proto_depIdxs,
		EnumInfos:         file_proto_getting_v1_auth_proto_enumTypes,
		MessageInfos:      file_proto_getting_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_getting_v1_auth_proto = out.File
	file_proto_getting_v1_auth_proto_goTypes = nil
	file_proto_getting_v1_auth_proto_depIdxs = nil
}
