// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/getting/v1/user.proto

package gettingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDto struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email  string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name   *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Status int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// epoch time in milliseconds
	Ctime         int64 `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDto) Reset() {
	*x = UserDto{}
	mi := &file_proto_getting_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDto) ProtoMessage() {}

func (x *UserDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDto.ProtoReflect.Descriptor instead.
func (*UserDto) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserDto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserDto) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserDto) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_proto_getting_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PageUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Status        *int32                 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageUserRequest) Reset() {
	*x = PageUserRequest{}
	mi := &file_proto_getting_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageUserRequest) ProtoMessage() {}

func (x *PageUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageUserRequest.ProtoReflect.Descriptor instead.
func (*PageUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *PageUserRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *PageUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PageUserRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Status        *int32                 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_getting_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type StreamListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Status        *int32                 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamListRequest) Reset() {
	*x = StreamListRequest{}
	mi := &file_proto_getting_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamListRequest) ProtoMessage() {}

func (x *StreamListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getting_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamListRequest.ProtoReflect.Descriptor instead.
func (*StreamListRequest) Descriptor() ([]byte, []int) {
	return file_proto_getting_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *StreamListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *StreamListRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

var File_proto_getting_v1_user_proto protoreflect.FileDescriptor

const file_proto_getting_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/getting/v1/user.proto\x12\n" +
	"getting.v1\x1a\x1cproto/getting/v1/basic.proto\x1a\x1bproto/getting/v1/page.proto\"\x7f\n" +
	"\aUserDto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x14\n" +
	"\x05ctime\x18\x05 \x01(\x03R\x05ctimeB\a\n" +
	"\x05_name\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x93\x01\n" +
	"\x0fPageUserRequest\x126\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x16.getting.v1.PaginationR\n" +
	"pagination\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x01R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_status\"m\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x01R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_status\"]\n" +
	"\x11StreamListRequest\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x01R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_status2\xc4\x01\n" +
	"\x04User\x128\n" +
	"\x03Get\x12\x1a.getting.v1.GetUserRequest\x1a\x13.getting.v1.UserDto\"\x00\x12<\n" +
	"\x06Update\x12\x1d.getting.v1.UpdateUserRequest\x1a\x11.getting.v1.Empty\"\x00\x12D\n" +
	"\n" +
	"StreamList\x12\x1d.getting.v1.StreamListRequest\x1a\x13.getting.v1.UserDto\"\x000\x01B\xa5\x01\n" +
	"\x0ecom.getting.v1B\tUserProtoP\x01Z?github.com/tsingson/grpc-rust-buf/go/proto/getting/v1;gettingv1\xa2\x02\x03GXX\xaa\x02\n" +
	"Getting.V1\xca\x02\n" +
	"Getting\\V1\xe2\x02\x16Getting\\V1\\GPBMetadata\xea\x02\vGetting::V1b\x06proto3"

var (
	file_proto_getting_v1_user_proto_rawDescOnce sync.Once
	file_proto_getting_v1_user_proto_rawDescData []byte
)

func file_proto_getting_v1_user_proto_rawDescGZIP() []byte {
	file_proto_getting_v1_user_proto_rawDescOnce.Do(func() {
		file_proto_getting_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_getting_v1_user_proto_rawDesc), len(file_proto_getting_v1_user_proto_rawDesc)))
	})
	return file_proto_getting_v1_user_proto_rawDescData
}

var file_proto_getting_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_getting_v1_user_proto_goTypes = []any{
	(*UserDto)(nil),           // 0: getting.v1.UserDto
	(*GetUserRequest)(nil),    // 1: getting.v1.GetUserRequest
	(*PageUserRequest)(nil),   // 2: getting.v1.PageUserRequest
	(*UpdateUserRequest)(nil), // 3: getting.v1.UpdateUserRequest
	(*StreamListRequest)(nil), // 4: getting.v1.StreamListRequest
	(*Pagination)(nil),        // 5: getting.v1.Pagination
	(*Empty)(nil),             // 6: getting.v1.Empty
}
var file_proto_getting_v1_user_proto_depIdxs = []int32{
	5, // 0: getting.v1.PageUserRequest.pagination:type_name -> getting.v1.Pagination
	1, // 1: getting.v1.User.Get:input_type -> getting.v1.GetUserRequest
	3, // 2: getting.v1.User.Update:input_type -> getting.v1.UpdateUserRequest
	4, // 3: getting.v1.User.StreamList:input_type -> getting.v1.StreamListRequest
	0, // 4: getting.v1.User.Get:output_type -> getting.v1.UserDto
	6, // 5: getting.v1.User.Update:output_type -> getting.v1.Empty
	0, // 6: getting.v1.User.StreamList:output_type -> getting.v1.UserDto
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_getting_v1_user_proto_init() }
func file_proto_getting_v1_user_proto_init() {
	if File_proto_getting_v1_user_proto != nil {
		return
	}
	file_proto_getting_v1_basic_proto_init()
	file_proto_getting_v1_page_proto_init()
	file_proto_getting_v1_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_getting_v1_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_getting_v1_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_getting_v1_user_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_getting_v1_user_proto_rawDesc), len(file_proto_getting_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_getting_v1_user_proto_goTypes,
		DependencyIndexes: file_proto_getting_v1_user_proto_depIdxs,
		MessageInfos:      file_proto_getting_v1_user_proto_msgTypes,
	}.Build()
	File_proto_getting_v1_user_proto = out.File
	file_proto_getting_v1_user_proto_goTypes = nil
	file_proto_getting_v1_user_proto_depIdxs = nil
}
