// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=.ts"
// @generated from file proto/getting/common/page.proto (package getting.common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/getting/common/page.proto.
 */
export const file_proto_getting_common_page: GenFile = /*@__PURE__*/
  fileDesc("Ch9wcm90by9nZXR0aW5nL2NvbW1vbi9wYWdlLnByb3RvEg5nZXR0aW5nLmNvbW1vbiJXCgpQYWdpbmF0aW9uEgwKBHBhZ2UYASABKAMSEQoJcGFnZV9zaXplGAIgASgDEigKCHNvcnRfYnlzGAMgAygLMhYuZ2V0dGluZy5jb21tb24uU29ydEJ5IkkKBlNvcnRCeRINCgVmaWVsZBgBIAEoCRIwCglkaXJlY3Rpb24YAiABKA4yHS5nZXR0aW5nLmNvbW1vbi5Tb3J0RGlyZWN0aW9uKmEKDVNvcnREaXJlY3Rpb24SHgoaU09SVF9ESVJFQ1RJT05fVU5TUEVDSUZJRUQQABIXChNTT1JUX0RJUkVDVElPTl9BU0NFEAESFwoTU09SVF9ESVJFQ1RJT05fREVTQxACQrMBChJjb20uZ2V0dGluZy5jb21tb25CCVBhZ2VQcm90b1ABWjlnaXRodWIuY29tL3RzaW5nc29uL2dycGMtcnVzdC1idWYvZ28vcHJvdG8vZ2V0dGluZy9jb21tb26iAgNHQ1iqAg5HZXR0aW5nLkNvbW1vbsoCDkdldHRpbmdcQ29tbW9u4gIaR2V0dGluZ1xDb21tb25cR1BCTWV0YWRhdGHqAg9HZXR0aW5nOjpDb21tb25iBnByb3RvMw");

/**
 * @generated from message getting.common.Pagination
 */
export type Pagination = Message<"getting.common.Pagination"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 page_size = 2;
   */
  pageSize: bigint;

  /**
   * @generated from field: repeated getting.common.SortBy sort_bys = 3;
   */
  sortBys: SortBy[];
};

/**
 * Describes the message getting.common.Pagination.
 * Use `create(PaginationSchema)` to create a new message.
 */
export const PaginationSchema: GenMessage<Pagination> = /*@__PURE__*/
  messageDesc(file_proto_getting_common_page, 0);

/**
 * @generated from message getting.common.SortBy
 */
export type SortBy = Message<"getting.common.SortBy"> & {
  /**
   * @generated from field: string field = 1;
   */
  field: string;

  /**
   * @generated from field: getting.common.SortDirection direction = 2;
   */
  direction: SortDirection;
};

/**
 * Describes the message getting.common.SortBy.
 * Use `create(SortBySchema)` to create a new message.
 */
export const SortBySchema: GenMessage<SortBy> = /*@__PURE__*/
  messageDesc(file_proto_getting_common_page, 1);

/**
 * @generated from enum getting.common.SortDirection
 */
export enum SortDirection {
  /**
   * @generated from enum value: SORT_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SORT_DIRECTION_ASCE = 1;
   */
  ASCE = 1,

  /**
   * @generated from enum value: SORT_DIRECTION_DESC = 2;
   */
  DESC = 2,
}

/**
 * Describes the enum getting.common.SortDirection.
 */
export const SortDirectionSchema: GenEnum<SortDirection> = /*@__PURE__*/
  enumDesc(file_proto_getting_common_page, 0);

